name: Build Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  essa tag permite executar o fluxo manualmente
  workflow_dispatch:

jobs:
  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref}}
          fetch-depth: 0

      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main
          prefix: v

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreplay.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'  

  backend-build-and-test:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Backend Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set .NET Core SDK version
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x.x'
          cache: true
          cache-dependency-path: ./backend/packages.lock.json

      - name: Restore .NET Core
        working-directory: ./backend
        run: |
          dotnet restore TodoApp.Api.slnx
      
      - name: Build .NET Core project
        working-directory: ./backend
        run: |
          dotnet build --no-restore TodoApp.Api.slnx

      - name: Tests
        working-directory: ./backend
        run: |
          dotnet test TodoApp.Api.slnx --no-restore --no-build  --configuration Release --logger trx --results-directory "TestResults"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dotnet-test-results
          path: backend/TestResults

  frontend-build-and-test:
    if: false
    runs-on: ubuntu-latest
    name: Build Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run build