name: Build Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  essa tag permite executar o fluxo manualmente
  workflow_dispatch:

jobs:
  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento
    permissions:
      contents: write

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref}}
          fetch-depth: 0

      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main
          prefix: v

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"

          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          git tag -a "${{ steps.version.outputs.version }}" \
            -m "Release ${{ steps.version.outputs.version }}"

          git push origin "${{ steps.version.outputs.version }}"
        if: github.ref == 'refs/heads/main'  

  backend-build-and-test:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Backend Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set .NET Core SDK version
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x.x'
          cache: true
          cache-dependency-path: ./backend/packages.lock.json

      - name: Restore .NET Core
        working-directory: ./backend
        run: |
          dotnet restore TodoApp.Api.slnx
      
      - name: Build .NET Core project
        working-directory: ./backend
        run: |
          dotnet build --no-restore --configuration Release TodoApp.Api.slnx

      - name: Tests
        working-directory: ./backend
        run: |
          dotnet test TodoApp.Api.slnx --no-restore --no-build --configuration Release --logger trx --results-directory "TestResults"

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: dotnet-test-results
          path: backend/TestResults

      - name: Publish
        working-directory: ./backend
        run: |
          dotnet publish TodoApp.Api.csproj \
            --no-restore \
            --no-build \
            --configuration Release \
            --output ./publish

      - name: Upload dotnet artifacts
        uses: actions/upload-artifact@v7
        with:
          name: api
          path: ./backend/publish

  frontend-build-and-test:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Frontend Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci
          
      - name: Build
        working-directory: ./frontend
        run: |
          npm run build

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v7
        with:
          name: frontend
          path: ./frontend/dist/frontend/browser

  dependency-check:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Dependency Check

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v5

  code-security-check:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Security Check

    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - csharp
          - javascript-typescript

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        if: matrix.language == 'csharp'
        uses: github/codeql-action/autobuild@v4

      - name: Analyze
        uses: github/codeql-action/analyze@v4

  build-backend-docker:
    needs: [versionamento, backend-build-and-test]
    runs-on: ubuntu-latest
    name: Backend Docker

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v7
        with:
          name: api
          path: ./backend
          run-id: ${{ github.run_id }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            fourtwodev/todo-app-api:${{ needs.versionamento.outputs.version }}
            fourtwodev/todo-app-api:latest

  build-frontend-docker:
    needs: [versionamento, frontend-build-and-test]
    runs-on: ubuntu-latest
    name: Frontend Docker

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v7
        with:
          name: frontend
          path: ./frontend
          run-id: ${{ github.run_id }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            fourtwodev/todo-app-frontend:${{ needs.versionamento.outputs.version }}
            fourtwodev/todo-app-frontend:latest